CREATE TABLE `article_overrides` (
	`id` text PRIMARY KEY NOT NULL,
	`slug` text,
	`collection` text,
	`title` text,
	`created` text,
	`updated` text,
	`branch` text,
	`subbranch` text,
	`stage` text,
	`validity` text,
	`category` text,
	`tags` text,
	`type` text,
	`project` text,
	`confidence` text,
	`source` text,
	`review_date` text,
	`summary` text,
	`next` text,
	`body` text,
	`deleted` integer DEFAULT false NOT NULL
);
