import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const articleOverrides = sqliteTable("article_overrides", {
  id: text("id").primaryKey(),
  slug: text("slug"),
  collection: text("collection"),
  title: text("title"),
  created: text("created"),
  updated: text("updated"),
  branch: text("branch"),
  subbranch: text("subbranch"),
  stage: text("stage"),
  validity: text("validity"),
  category: text("category"),
  tags: text("tags"),
  type: text("type"),
  project: text("project"),
  confidence: text("confidence"),
  source: text("source"),
  reviewDate: text("review_date"),
  summary: text("summary"),
  next: text("next"),
  body: text("body"),
  deleted: integer("deleted", { mode: "boolean" }).notNull().default(false),
});
