[package]
name = "life-strategy-library"
version = "0.2.2"
description = "本地优先的私人思考花园"
authors = ["Muyuxiaoluo"]
edition = "2021"

[lib]
name = "life_strategy_library_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-process = "2.3.1"
tauri-plugin-sql = { version = "2.4.0", features = ["sqlite"] }
tauri-plugin-updater = "2.10.1"
